"""Create binaries that generate code, and rules that run those binaries.

The rules generated by `dart_codegen_rule` have the following arguments:

- generate_for: Optional. The Dart source files which will have associated
  generated files. If `generated_for` is not provided everying in `srcs` will be
  considered an input. One of `generate_for` or `srcs` must be provided.
- srcs: Optional. Dart source files which may be inputs to the code generation,
  or may be imported by other code but does not exist in a separate build
  target.
- forced_deps: Optional. All files from these deps will be provided as inputs to
  the codegen actions.
- generator_args: Arbitrary arguments which can be passed to the codegen binary.
"""

load(":_codegen_binary.bzl", "dart_codegen_binary")
load(":_codegen_rule.bzl", "dart_codegen_rule")
load(":_codegen_aspect.bzl", "dart_codegen_aspect")
