load("//dart/build_rules:vm.bzl", "dart_vm_binary")

package(default_visibility = ["//visibility:public"])

dart_vm_binary(
    name = "generate_copyright",
    srcs = ["bin/generate_copyright.dart"],
    script_file = "bin/generate_copyright.dart",
)
