load("//dart/build_rules:core.bzl", "dart_library")
package(default_visibility = ["//visibility:public"])

dart_library(
    name = "server",
    srcs = [
        "bin/server.dart",
    ],
    deps = [
        "//vendor/path",
        "//vendor/shelf",
        "//vendor/shelf_static",
    ],
)
