package(default_visibility = ["//visibility:public"])

# TODO: Use the ddc support files from the sdk once available.
#       See https://github.com/dart-lang/sdk/issues/27001
filegroup(
    name = "ddc_support",
    srcs = glob(["ddc_support/*.*"]),
)
